package io.Depth_Unknown.game.settings;

import com.badlogic.gdx.Preferences;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.ui.*;
import com.badlogic.gdx.scenes.scene2d.utils.ChangeListener;

/**
 * This allows multiple subtypes like arraylists have
 * Created with assistance from ChatGpt
 * */
public class Setting<T> {
    private final String key;
    private T value;
    private final T defaultValue;
    Preferences settings;

    public Setting(String key, T defaultValue, Preferences settings) {
        this.key = key;
        this.defaultValue = defaultValue;
        this.settings = settings;
        loadValue();
    }

    public void setValue(T value) {
        this.value = value;
        saveValue();
    }

    public T getValue() {
        return value;
    }

    /**
     * Generated by ChatGPT
     * */
    public void loadValue() {
        if (defaultValue instanceof Boolean) {
            value = (T) Boolean.valueOf(settings.getBoolean(key, (Boolean) defaultValue));
        } else if (defaultValue instanceof Integer) {
            value = (T) Integer.valueOf(settings.getInteger(key, (Integer) defaultValue));
        } else if (defaultValue instanceof Float) {
            value = (T) Float.valueOf(settings.getFloat(key, (Float) defaultValue));
        } else if (defaultValue instanceof String) {
            value = (T) settings.getString(key, (String) defaultValue);
        } else {
            throw new RuntimeException("Load Unsupported type for setting: " + defaultValue.getClass());
        }
    }

    public void saveValue() {
        if (defaultValue instanceof Boolean) {
            settings.putBoolean(key, (Boolean) value);
        } else if (defaultValue instanceof Integer) {
            settings.putInteger(key, (Integer) value);
        } else if (defaultValue instanceof Float) {
            settings.putFloat(key, (Float) value);
        } else if (defaultValue instanceof String) {
            settings.putString(key, (String) value);
        } else {
            System.err.println("Save Unsupported type for setting: " + defaultValue.getClass());
        }
    }
    public Label getLabel() {
        return new Label(key, new Label.LabelStyle(new BitmapFont(), Color.WHITE));
    }
    public Actor getActor(Skin skin) {
        if (value instanceof Boolean) {
            CheckBox checkBox = new CheckBox("", skin);
            checkBox.setChecked((Boolean) value);
            checkBox.addListener(new ChangeListener() {
                @Override
                public void changed(ChangeEvent event, Actor actor) {
                    setValue((T) Boolean.valueOf(checkBox.isChecked()));
                    System.out.println("Changed value: " + value);
                }
            });
            return checkBox;

        } else if (value instanceof Float) {
            Slider slider = new Slider(0f, 1f, 0.01f, false, skin);
            slider.setValue((Float) value);
            slider.addListener(new ChangeListener() {
                @Override
                public void changed(ChangeEvent event, Actor actor) {
                    setValue((T) Float.valueOf(slider.getValue()));
                    System.out.println("Changed value: " + value);
                }
            });
            return slider;

        } else if (value instanceof Integer) {
            // Could use a Slider or SelectBox
            Slider slider = new Slider(0, 100, 1, false, skin);
            slider.setValue((Integer) value);
            slider.addListener(new ChangeListener() {
                @Override
                public void changed(ChangeEvent event, Actor actor) {
                    setValue((T) Integer.valueOf((int) slider.getValue()));
                    System.out.println("Changed value: " + value);
                }
            });
            return slider;

        } else if (value instanceof String) {
            TextField field = new TextField((String) value, skin);
            field.addListener(new ChangeListener() {
                @Override
                public void changed(ChangeEvent event, Actor actor) {
                    setValue((T) field.getText());
                    System.out.println("Changed value: " + value);
                }
            });
            return field;

        } else {
            System.err.println("Actor Unsupported type for setting: " + value.getClass());
            return null;
        }
    }
}
